# Generated by Django 3.1.2 on 2020-10-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PitchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
    ]
