# Generated by Django 3.1.2 on 2020-11-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PitchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='audio_files/', verbose_name='Audio File'),
        ),
    ]
