# Generated by Django 3.1.2 on 2020-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PitchApp', '0002_auto_20201027_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
    ]
